name: Cushier
description: Cushier adalah aplikasi pengelolaan usaha serta Point of Sale (POS) berbasis cloud yang mudah digunakan tanpa perlu proses yang ribet sehingga cocok untuk bidang usaha apapun.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: 3.2.4495
  font_awesome_flutter: ^8.5.0
  
  # Firebase
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  # firestore_ui: ^1.7.2
  # firebase_storage: ^3.0.6

  # Functional
  shared_preferences: ^0.5.3
  provider: ^3.1.0
  http: ^0.12.0
  barcode_scan: ^1.0.0
  flutter_html: ^0.8.2
  audioplayers: ^0.13.1
  timeago: ^2.0.19

  # UI
  intervalprogressbar: ^1.0.1
  datetime_picker_formfield: ^0.4.3
  tutorial_coach_mark: ^0.2.0
  percent_indicator: ^2.1.1
  expandable: ^3.0.0
  showcaseview: ^0.1.3
  badges: ^1.1.0
  flash: ^1.1.0
  flutter_circular_chart: ^0.1.0
  bezier_chart: ^1.0.14
  theme_provider: ^0.3.1
  auto_size_text: ^2.1.0
  custom_radio_grouped_button: ^1.0.0
  bubble_tab_indicator: ^0.1.4

  popup_menu: ^1.0.3
  launch_review: ^1.0.1
  preload_page_view: ^0.1.4
  numberpicker: ^1.1.0
  super_tooltip: ^0.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
  - assets/butt_press.wav
  - assets/scan_beep.mp3
  - assets/scan_error.wav
  - images/anon.png
  - images/dummy.png
  - images/logo.png
  - images/onboarding/pos.png
  - images/onboarding/inventory.png
  - images/onboarding/cloud.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-Bold.ttf
          weight: 600
        - asset: fonts/Lato-Black.ttf
          weight: 800
    - family: FlamanteRoma
      fonts:
        - asset: fonts/Flamante-Roma-Medium.ttf
        - asset: fonts/Flamante-Roma-MediumItalic.ttf
          style: italic
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Regular.ttf
    - family: NovaMono
      fonts:
        - asset: fonts/NovaMono-Regular.ttf
    - family: OxygenMono
      fonts:
        - asset: fonts/OxygenMono-Regular.ttf
    - family: saxMono
      fonts:
        - asset: fonts/saxmono.ttf
    - family: ShareTechMono
      fonts:
        - asset: fonts/ShareTechMono-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
